language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t ryanlatini/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ryanlatini/docker-react npm run test -- --coverage